name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Assalamualaikum, thanks for your contribution, we still under developing process and have some issues, so thanks for cooperating'
        pr-message: 'Assalamualaikum, thank you for your contribution for this project, Lets get to work. First, Data gathering'
